---
name: RPM build in Fedora Project COPR
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Submit a build from Fedora Container
    container: fedora:latest
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v1

      - name: Install API Token for copr-cli
        env:
          API_TOKEN_CONTENT: ${{ secrets.COPR_CLI_TOKEN }}
        run: |
          mkdir -p "$HOME/.config"
          echo "$API_TOKEN_CONTENT" > "$HOME/.config/copr"

      - name: Install tooling for source RPM build
        run: |
          dnf -y install @development-tools @rpm-development-tools
          dnf -y install copr-cli make

      - name: Build the source RPM
        run: cd rpm && make srpm

      - name: Submit the build by uploading the source RPM
        run: copr build sparticvs/owasp-threat-dragon rpm/*.src.rpm
